### PR TITLE
Update Gitter URL

### PR DESCRIPTION
**Pull request by cdevienne**
Hi @aacanakin 

I think the gitter should be moved too. 
If you agree could you setup the new gitter forum (I cannot do it) and merge this PR ?

Thanks!

Christophe

### CODE REVIEW

**Comment by aacanakin** [comment]
Hi @cdevienne, I can't create a gitter.im orgranization currently. The site seems to be bugged.

**Comment by cdevienne** [comment]
Thanks for the update

**Comment by cdevienne** [comment]
Hi @aacanakin, any luck in moving the gitter ?

**Comment by aacanakin** [comment]
@cdevienne gitter is not seeing my organizations even if I changed the permissions. Moreover, I need to use this organization for other purposes. Will it be ok for you if I move this repo back to my account?

**Comment by cdevienne** [comment]
I liked the project being on an organization account and moving the project every month is not what I had in mind ^^

That said if you really need to get it out of slicebit... your decision.

**Comment by cdevienne** [comment]
Hi @aacanakin 

Any update on the subject ? Do you still intend to move qb out of slicebit ?

Cheers,

Christophe

**Comment by aacanakin** [comment]
I moved this repo back to my personal account. @cdevienne I think you need to update yago dependencies. Sorry for that.

**Pull request closed without merging**
